---
# New Relic Database Monitoring Configuration
# Copy this to databases.yml and update with your actual database details

# New Relic Configuration
newrelic_license_key: "YOUR_NEWRELIC_LICENSE_KEY"
newrelic_account_id: "YOUR_ACCOUNT_ID"
newrelic_region: "US"  # US or EU

# Environment settings
environment: production
aws_region: us-east-1

# Custom attributes for all monitored resources
custom_attributes:
  team: database-team
  cost_center: engineering

# MySQL Databases
mysql_databases:
  - host: mysql-prod-01.example.com
    port: 3306
    user: newrelic
    password: "secure_password_here"
    service_name: mysql-prod-webapp
    environment: production
    extended_metrics: true
    interval: 30s
    # Query performance monitoring settings
    enable_query_monitoring: true
    query_metrics_interval: 60s
    max_sql_query_length: 1000
    gather_query_samples: true
    custom_labels:
      application: webapp
      tier: primary
      region: us-east-1
    tls_enabled: true
    
  - host: mysql-prod-02.example.com
    port: 3306
    user: newrelic
    password: "another_password"
    service_name: mysql-prod-analytics
    environment: production
    extended_metrics: true
    custom_labels:
      application: analytics
      tier: replica
      region: us-east-1

  - host: mysql-dev.example.com
    port: 3306
    user: newrelic
    password: "dev_password"
    service_name: mysql-dev
    environment: development
    extended_metrics: false
    interval: 60s
    custom_labels:
      application: webapp
      tier: development

# PostgreSQL Databases
postgresql_databases:
  - host: postgres-prod-01.example.com
    port: 5432
    user: newrelic
    password: "pg_secure_password"
    database: production_db
    service_name: postgres-prod-main
    environment: production
    sslmode: require
    collect_bloat_metrics: true
    collect_db_lock_metrics: true
    interval: 30s
    # Query performance monitoring settings
    enable_query_monitoring: true
    query_metrics_interval: 60s
    max_sql_query_length: 1000
    # Note: Requires pg_stat_statements extension and proper permissions
    custom_labels:
      application: main-app
      tier: primary
      region: us-east-1
    
  - host: postgres-analytics.example.com
    port: 5432
    user: newrelic
    password: "analytics_password"
    database: analytics
    service_name: postgres-analytics
    environment: production
    sslmode: prefer
    collection_list: "ALL"
    custom_labels:
      application: data-warehouse
      tier: analytics
      region: us-west-2

  - host: postgres-dev.example.com
    port: 5432
    user: newrelic
    password: "dev_pg_password"
    database: development
    service_name: postgres-dev
    environment: development
    sslmode: disable
    interval: 60s
    custom_labels:
      application: all
      tier: development